splash = false
preload = /home/wojtas/Pictures/wallpapers/raiden.jpg
#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = DP-1, /home/wojtas/Pictures/wallpapers/raiden.jpg
#if more than one monitor in use, can load a 2nd image
# wallpaper = monitor2,/path/to/next_image.png
# .. more monitors